.TH XML-XREAD "1" "July 2004" "1.1" "User Commands"
.SH NAME
xml-xread \- Parse XML documents with entity and URI resolution
.SH SYNOPSIS
.B xml-xread
\fR[\fIoptions\fR] \fIxmlfile\fR
.SH DESCRIPTION
xml-xread is a simple command line tool for parsing and validating
XML documents.  It is not an actual XML parser, it just wraps around
a JAXP XMLReader, adding support for catalog-based entity and URI
resolution.
.SH OPTIONS
.TP
\fB\-c\fR \fIcatalogfile\fR
Load a particular catalog file.  May be specified multiple times.
.TP
\fB\-v\fR
Perform a validating parse.  This is the default.
.TP
\fB\-w\fR
Perform a well-formed parse, not a validating parse.
.TP
\fB\-N\fR
Perform a namespace-aware parse.  This is the default.
.TP
\fB\-n\fR
Perform a namespace-ignorant parse.
.TP
\fB\-d\fR \fIdebuglevel\fR
Set the debug level (an integer).  Warnings are shown if the debug
level is set to greater than 2.
.TP
\fB\-E\fR \fImaxerrors\fR
Set the maximum number of errors to display.  The default is 10.
.SH FILES
.B __RESOLVERDIR__/CatalogManager.properties
.RS
The central catalog manager configuration file used by \fBxml-xread\fR.
.SH "SEE ALSO"
.BR xml-parse (1),
.BR xml-resolver (1),
.BR java (1),
the OASIS entity resolution technical committee home page at
<http://www.oasis-open.org/committees/entity/>.
.SH AUTHOR
Norman Walsh <Norman.Walsh@Sun.COM>
